spring.application.name=portfolio-backend

# Połączenie z bazą danych PostgreSQL w Dockerze
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=superhaslo

# Automatyczne tworzenie tabel w bazie przez Springa
spring.jpa.hibernate.ddl-auto=update

# Wyświetlanie zapytań SQL w konsoli (przydatne do nauki i debugowania)
spring.jpa.show-sql=true
